before_install:
  - git fetch --tags
  - sbt ci/generateScripts
  - ci/tests/build_image

stages:
  - name: Test
  - name: Release
    if: ((branch = master) OR (tag IS present)) AND NOT fork

services:
  - docker

os: linux
dist: trusty
language: scala
jdk: openjdk8
scala:
  - 2.13.1

jobs:
  include:
    - name: test-probe @ scala-2.12
      script: ci/tests/run probe 2.12.10
    - name: test-scala @ scala-2.12
      script: ci/tests/run scala 2.12.10
    - stage: Release
      name: Release
      script: sbt ci-release
