before_install:
  - git fetch --tags
  - sbt ci/generateScripts
  - docker build --tag testimage .

branches:
  only:
    - master

stages:
  - name: Test
  - name: Release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork


services:
  - docker

os: linux
language: scala
jdk: openjdk8
scala:
  - 2.13.1

jobs:
  include:
    - name: test-probe @ scala-2.12
      script: sh ci/run_docker sh ci/2.12.10/test-probe
    - name: test-probe @ scala-2.13
      script: sh ci/run_docker sh ci/2.13.1/test-probe
    - name: test-scala @ scala-2.12
      script: sh ci/run_docker sh ci/2.12.10/test-scala
    - name: test-scala @ scala-2.13
      script: sh ci/run_docker sh ci/2.13.1/test-scala
    - stage: Release
      script: sbt ci-release